backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "../src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Stack", name: "stack", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Thumbnail Image",name: "thumb",widget: "image"}
      - {label: "Featured Image",name: "feature",widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}